### ISSUE TITLE
Using Google CDN makes page load for 2+ minutes in China

### ISSUE THREAD

**Issue by paulvi** [mojohaus/mojohaus.github.io#11]
Using Google make page load for 2+ minutes in China

This is of course, issue of site plugin. Cat you point to the exact location?

![mojohause-site](https://cloud.githubusercontent.com/assets/1614482/14696404/5e0375be-07ad-11e6-89b4-f0c0d0813dfb.png)

**Comment by paulvi** [comment]
well, it is not solved really, Google CDN are not available in China

**Comment by slachiewicz** [comment]
This is out of our control - we are using GitHub site hosting

**Comment by paulvi** [comment]
website is not fully hosted, some pieces distributed not via GitHub CDN, but from Google CDN

If any script from 3rd party CDN is loaded not async, then failure to load it for any reason, will block displaying of the page

Exactly on the example above, it takes 2 minute before page is displayed.
Basically most Chinese users would have left already site that is "not optimized for China"

The problem manifestation are any link to *.google.com or *.gstastic.com

See https://no-google-in-china.github.io/
