### ISSUE TITLE
apt-maven-plugin not working with JDK 8

### ISSUE THREAD

**Issue by shaunthomas999** [mojohaus/mojohaus.github.io#12]
I am not able to use org.codehaus.mojo:apt-maven-plugin:1.0-alpha-5 with JDK 8. I get the following error while trying to perform a maven build.

[ERROR] Failed to execute goal org.codehaus.mojo:apt-maven-plugin:1.0-alpha-5:process (process) on project _<project_name>_: Unable to locate the apt compiler in:
[ERROR] /Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/jre/../lib/tools.jar
[ERROR] Please ensure you are using JDK 1.5 or above and
[ERROR] not a JRE (the com.sun.tools.apt.Main class is required).

The problem seems to be because APT compiler has been integrated into javac in JDK 8 and it cannot be invoked via tools.jar.

Using lower versions of JDK is not an option for me as I have some project features which needs JDK 8.

**Comment by andham** [comment]
This issue should be filed with the apt-maven-plugin project, not this top project. However, I can't find the repo - does anyone know where it is? Maybe it wasn't moved and is dead?
