### ISSUE TITLE
useLastCommittedRevision parameter is not working in buildnumber-maven-plugin 

### ISSUE THREAD

**Issue by kuraidai** [mojohaus/mojohaus.github.io#14]
Hi,

I found the useLastCommittedRevision parameter is not working in the buildnumber-maven-plugin at least for the goal "create". Looking into the source code I doubt there is a defect.

Setting the useLastCommittedRevision parameter in my project's maven pom file, and run the "create" goal, the value will be passed to the field useLastCommittedRevision in the class CreateMojo. The value is correct until before calling the method getScmRevision() in the class CreateMojo. But once it enters the getScmRevision() method which is in the AbstractScmMojo class, the value useLastCommittedRevision is overwritten to the default value as false. 

I think because in the class AbstractScmMojo, the same parameter is defined as below and it has the problem.

```
@Parameter( property = "maven.buildNumber.useLastCommittedRevision", defaultValue = "false" )
private boolean useLastCommittedRevision;
```

Proposed fix is to remove the parameter definition from CreateMojo, since this parameter useLastCommittedRevision is not used in CreateMojo but only used in AbstractScmMojo.

**Comment by andham** [comment]
If this is still a problem the issue should be filed on the buildnumber-maven-plugin: https://github.com/mojohaus/buildnumber-maven-plugin/issues
