### ISSUE TITLE
native-maven-plugin unavailable on GitHub

### ISSUE THREAD

**Issue by gchauvet** [mojohaus/mojohaus.github.io#15]
Dear mojohaus Team,

According to page :
http://www.mojohaus.org/maven-native/native-maven-plugin/source-repository.html

The corresponding GIT repository is not (yet ?) available on GitHub :
https://github.com/mojohaus/maven-native/native-maven-plugin

Regards,

**Comment by gchauvet** [comment]
It seems it is a misspelling in URL : 
https://github.com/mojohaus/maven-native          (/native-maven-plugin)

**Comment by andham** [comment]
Please file this issue on the maven-native project: https://github.com/mojohaus/maven-native/issues
