### ISSUE TITLE
http://www.mojohaus.org/plugins.html How to find sources for plugins listed, e.g. 

### ISSUE THREAD

**Issue by paulvi** [mojohaus/mojohaus.github.io#16]
http://www.mojohaus.org/plugins.html  
How to find sources for plugins listed, e.g. `selenium-maven-plugin`

ref https://github.com/SeleniumHQ/selenium/issues/686#issuecomment-312583819

**Comment by andham** [comment]
Questions like this is better to ask on the mailing list: http://www.mojohaus.org/mail-lists.html

Typically, info about the source repo can be found in the docs for the maven plugin. I couldn't find them for the selenium plugin but here's an example from another plugin: http://www.mojohaus.org/findbugs-maven-plugin/source-repository.html
