### ISSUE TITLE
Plugin submission - reusable ide preferences

### ISSUE THREAD

**Issue by rombert** [mojohaus/mojohaus.github.io#22]
Hi,

I'd prepared a submission for a new Maven plugin that allows simple management of IDE preferences by deploying them as Maven artifacts and allowing them to be applied using Maven goals.

I've previously posted on the dev mailing list - https://groups.google.com/forum/#!topic/mojohaus-dev/EhFkWJ8V-rc .

The plug-in source code is attached. It is licensed to MojoHaus under the Apache License 2.0 .

[reusable-ide-preferences.zip](https://github.com/mojohaus/mojohaus.github.io/files/1394242/reusable-ide-preferences.zip)

**Comment by olamy** [comment]
all done: https://github.com/mojohaus/reusable-ide-preferences
@rombert you should have received an invite.
