### ISSUE TITLE
null (org.codehaus.mojo:jaxb2-maven-plugin:2.2:xjc:xjc:generate-sources) 

### ISSUE THREAD

**Issue by Arulselvanl** [mojohaus/mojohaus.github.io#26]
I have the below in the pom.xml, but getting an error in the line of "execution" - 

null (org.codehaus.mojo:jaxb2-maven-plugin:2.2:xjc:xjc:generate-sources) org.apache.maven.plugin.MojoExecutionException at 
 org.codehaus.mojo.jaxb2.javageneration.AbstractJavaGeneratorMojo.performExecution(AbstractJavaGeneratorMojo.java:482) at 

<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>jaxb2-maven-plugin</artifactId>
				<version>2.2</version>
				<executions>
					<execution>
						<id>xjc</id>
						<goals>							
							<goal>xjc</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<schemaDirectory>${project.basedir}/src/main/resources/xsd</schemaDirectory>
					<outputDirectory>${project.basedir}/src/main/java</outputDirectory>
					<clearOutputDir>false</clearOutputDir>
					<packageName>com.domain.test</packageName>					
                    <sources>
                        <source>src/main/resources/xsd/POSSvcsSchemaPOSInstallApptStatusSchema.xsd</source>
                    </sources>                	 
                </configuration>
			</plugin>

**Comment by andham** [comment]
If you think this is a bug you should report it on the correct repo (https://github.com/mojohaus/jaxb2-maven-plugin). If it's a question you should ask on the users list (see http://www.mojohaus.org/jaxb2-maven-plugin/Documentation/v2.3.1/mail-lists.html).
