### ISSUE TITLE
Java code generation incomplete

### ISSUE THREAD

**Issue by DietrichUnverzagt** [mojohaus/mojohaus.github.io#32]
[gdv_typen2003.zip](https://github.com/mojohaus/mojohaus.github.io/files/3039012/gdv_typen2003.zip)
I tried to transform the attached xsd to Java. the XSD file contains lots of simple types which should be transformed to java Enums. However, only 5 Java classes out of ~hundreds were generated.

What is going wrong?

Using:

<dependency>
    		<groupId>org.codehaus.mojo</groupId>
    		<artifactId>jaxb2-maven-plugin</artifactId>
    		<version>2.4</version>
</dependency>	
.
.
.
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>jaxb2-maven-plugin</artifactId>
				
				<executions>
					<execution>
						<id>xjc</id>
						<goals>
							<goal>xjc</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					
					<outputDirectory>${project.basedir}/src/main/java</outputDirectory>
					<clearOutputDir>false</clearOutputDir>
				</configuration>
			</plugin>

**Comment by andham** [comment]
This should be filed with the jaxb2-maven-plugin, which has its own git repo and issue tracker.
https://github.com/mojohaus/jaxb2-maven-plugin/issues
