### ISSUE TITLE
Maven plugin links are broken

### ISSUE THREAD

**Issue by rombert** [mojohaus/mojohaus.github.io#4]
Trying to follow links from http://www.mojohaus.org/plugins.html leads to a 404

**Comment by khmarbaise** [comment]
Here it works without any problems...

**Comment by dantran** [comment]
I also see the same error

**Comment by rombert** [comment]
To be more precise
- navigate to http://www.mojohaus.org/plugins.html
- click the jboss-packaging link , which leads to http://www.mojohaus.org/jboss-packaging-maven-plugin/
- note that a 404 is returned

**Comment by dennisl** [comment]
Yes, that is correct. We are still in the progress of deciding which plugins to migrate over from Codehaus. The plugins that have not yet been migrated will lead to a 404 at Mojohaus.

**Comment by Lonzak** [comment]
One more dead : http://www.mojohaus.org/ship-maven-plugin/
It has been nearly two years - so did you make a decision regarding the dead links? You should at least move those projects to the graveyard...

**Comment by andham** [comment]
#10 is a better report of the same problem. Closing this one.
