### ISSUE TITLE
Doxia Macro for plugins page

### ISSUE THREAD

**Issue by ebarboni** [mojohaus/mojohaus.github.io#5]
Hi,
 I would like to help for the mojohaus web site. I try to write a doxia macro (see https://github.com/ebarboni/mojopagepluginsgen) to get information for maven central using Rest Api (http://search.maven.org/#api). 
- This allow to get the last version of a released plugin 
- This allow to get a pom 

In gray => no url or no issue management
In orange => url pointing to codehaus.org.

I had to migrate the apt to xdoc because the macro was disturbing the table layout.

you can test is with : mvn clean install site.

It's work in progress. 
If usefull any idea welcome.

**Comment by andham** [comment]
As I understand it, this would fetch version info during site build and it would then require a new mojo site build whenever we do a release. In that case #19 is a better solution. Closing but feel free to request reopen if you don't agree.
