### ISSUE TITLE
xmlbeans-maven-plugin is not compatible with latest xmlbeans version 5.0.3

### ISSUE THREAD

**Issue by riteshk7j** [mojohaus/mojohaus.github.io#54]
I want to upgrade xmlbeans to latest available version 5.0.3. But when I am trying to generate the source from xsd files using this plugin. I am getting below error:

`..\xml-model\target\generated-sources\xmlbeans\com\metasolv\oms\orderModel\x2002\x06\x25\SystemHealthPoliciesType.java:144: error: cannot find symbol
        public static com.metasolv.oms.orderModel.x2002.x06.x25.SystemHealthPoliciesType parse(org.apache.xmlbeans.xml.stream.XMLInputStream xis) throws org.apache.xmlbeans.XmlException, org.apache.xmlbeans.xml.stream.XMLStreamException {
                                                                                                                             ^
  symbol:   class XMLInputStream
  location: package org.apache.xmlbeans.xml.stream `
  
  Is there any other compatible version of this plugin available to achieve this? Or, is there some other plugin altogether to generate the sources.

**Comment by slawekjaranowski** [comment]
Did you think about: https://xmlbeans.apache.org/guide/Maven.html
